# Generated by Django 6.0.3 on 2026-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('Curd', 'Curd'), ('Milk', 'Milk'), ('Lassi', 'Lassi'), ('Milkshake', 'Milkshake'), ('Panner', 'Panner'), ('Ghee', 'Ghee'), ('Cheese', 'Cheese'), ('Ice-creams', 'Ice-creams')], max_length=10)),
                ('product_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
